config/routes.rb
Rails.application.routes.draw do
  
  resources :boards do
    resources :songs
  end
  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  def add_artist_to_song

    # find songs that arist 
    # /boards/1/songs/1
    # @song
    
    # .update(@artist)
  end

end

app/models/board.rb
class Board < ApplicationRecord
  has_many :songs, dependent: :destroy

  def by_rank(songs)
    
    # Song.order(:rank)
    songs.order(:rank)
  end
  # self.songs.sort_by { |song| song[:rank]}
  # self.songs.sort_by { |song| song[:rank]}
  # self.songs.order(:rank)
  # self.order(self.songs.rank)
  # self.order(:rank)
  # self.order(songs.rank)
  # self.order(songs.rank :asc)
  # self.order(:rank)
  
  def show_all_songs
    @all_songs = Songs.all
  end
end

app/models/change_title_to_title.rb
class ChangeTitleToTitle < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :board
  belongs_to :artist, optional: true

  # # called on a class Person.by_first_name
  def by_name
    self.name
  end
  # self.order(:rank)
  # Song.order(:rank)
  # def set_song
  #   if @artist
  #     @song = Song.new
  #   else
  #     @song = @board.songs.new
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist_id, only: [:show, :edit, :update, :destroy]
  # before_action :set_song_id
  def index
    @artists = Artist.all
  end

  def create
    @artist = Artist.new(artist_params)
    ## Need to update song[:id] with artist
    # @artist.add_artist_to_song

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
  # def set_song_id
  #   @song = Song.find(params[:song_id])
  # end

  def set_artist_id
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board_id, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def show
    # @board.songs = @board.songs.order(:rank)
    # @board.songs = @board.songs.sort_by { |song| song[:rank]}
    # @board
    # @board.songs.order(:rank)
    # @board = Board.includes(:song).order("songs.rank asc")
    # Board.all.by_rank
    # Board.songs.by_rank
    # @board.sort
    @ranks = @board.by_rank(@board.songs)
    # by_rank
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def set_board_id
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action  :set_board_id, except: [:new]
  before_action :set_song_id, only: [:show, :edit, :update, :destroy]
 
  def index
    @songs = @board.songs
    # @songs_with_artist = @artist.songs
    @all_songs = Song.all
  end

  def create
    @song = @board.songs.new(song_params)

    if @song.save
      redirect_to [@board, @song]
      # board_song_path(@board, @song)
    else
      render :new
    end
  end

  def new
    if @board
      @song = @board.songs.new
    else
      @song = Song.new
      
    end
    # @song = @board.songs.new
    # @song = Song.new
    # @song.set_song
    # render 'layouts/song-form'
  end

  def show
    
  end

  

  def edit
    # render partial: 'layouts/song-form'
  end

  def update
    if @song.update(song_params)
      redirect_to [@board, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to board_songs_path
  end

  private

  def set_song_id
    @song = Song.find(params[:id])
  end

  def set_board_id
    @board = Board.find(params[:board_id])
  end 
  # def set_all_songs
  #   @all_songs = Board.songs
  # end

  # t.string "name"
  # t.string "rank"
  # t.bigint "board_id"
  # t.bigint "artist_id"
  # t.datetime "created_at", null: false
  # t.datetime "updated_at", null: false
  # t.index ["artist_id"], name: "index_songs_on_artist_id"
  # t.index ["board_id"], name: "index_songs_on_board_id"
  def song_params
    params.require(:song).permit(:name, :rank)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<%= render 'layouts/art-form' %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |a| %>
  <%= link_to a.name, artist_path(a) %><br/>
<% end %>

app/views/artists/new.html.erb
<h1>Artists</h1>
<%= render 'layouts/art-form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<%= link_to 'All Songs', artist_songs_path(@artist) %>
<%= link_to 'Add new song', new_artist_song_path(@artist) %>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

app/views/boards/edit.html.erb
<%= render 'layouts/form' %>

app/views/boards/index.html.erb
<h1>All Billboards</h1>

<% @boards.each do |b| %>
  <ul>
    <li><%= link_to b.title, board_path(b) %>  |  <%= link_to 'Edit Board Title', edit_board_path(b) %>  |  <%= link_to "Delete Board", b, method: :delete  %></li>
  </ul>
<% end %>

app/views/boards/new.html.erb
<%= render 'layouts/form' %>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>



<%= link_to 'All Songs', board_songs_path(@board) %>
<%= link_to 'Add new song', new_board_song_path(@board) %>
<ol>

<% @ranks.each do |song| %>

  <li><strong>Song Title:</strong> <%= link_to song.name, board_song_path(@board, song) %> | <strong>Rank:</strong> <%= song.rank %></li>
 
<% end %>
</ol>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>

app/views/layouts/_art-form.html.erb
<div class="form-wrapper">

<h1><%= @artist.id ? "Edit Artist Name" : "Create New Artist" %> </h1>

  <%= form_for @artist do |a| %> 
    <%= a.label :name %>
    <%= a.text_field :name %>
    <%= a.submit %>
  <% end %>
</div>

app/views/layouts/_form.html.erb
<div class="form-wrapper">
<h1><%= @board.id ? "Edit Board" : "Create New Board" %> </h1>

  <%= form_for @board do |b| %> 
    <%= b.label :title %>
    <%= b.text_field :title %>
    <%= b.submit %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<%= link_to 'BILLBOARDS', boards_path %>
<%= link_to 'CREATE NEW BOARD', new_board_path %>
<%= link_to 'CREATE NEW ARTIST', new_artist_path %>
<%= link_to 'ALL ARTIST', artists_path %>

app/views/layouts/_song-form.html.erb
<div class="form-wrapper">
<h1>Add Song Form</h1>

  <%= @board.id ? form_for [@board, @song]  do |s| : form_for [@artist, @song] do |s| %> 
    <%= s.label :name %>
    <%= s.text_field :name %>
    <%= s.label :rank %>
    <%= s.text_field :rank %>
    <%= s.submit %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<%= render 'layouts/song-form' %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<ol>
  <% @all_songs.each do |s| %>
   <li> <%= s.name %></li>
  <% end %>
    
</ol>

app/views/songs/new.html.erb
<h1>Songs</h1>
<%= render 'layouts/song-form' %>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>

<%= link_to 'Edit Song', edit_board_song_path(@song) %>
<%= link_to 'CREATE NEW ARTIST', new_song_artist_path(@song) %>